title:             Gin&Sugary
email:             402119383@qq.com
description:       This is our secret base where we post our memories and love.
author:            Xiaofeng Cai
# baseurl:           ""
url:               "https://xiaofeng96.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
